settings:
  title: 'Mobile payment solutions - Status page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: my-mps-emi-com
    name: my.mps-emi.com
    description: ''
    url: 'https://my.mps-emi.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: terminal-mps-emi-com
    name: terminal.mps-emi.com
    description: ''
    url: 'https://terminal.mps-emi.com/health-check'
    method: GET
    expectStatus: 200
    linkable: false

  - id: app-mps-emi-com
    name: app.mps-emi.com
    description: ''
    url: 'https://app.mps-emi.com/health-check'
    method: GET
    expectStatus: 200
    linkable: false

  - id: openbanking-mps-emi-com
    name: openbanking.mps-emi.com
    description: ''
    url: 'https://openbanking.mps-emi.com/swagger/index.html'
    method: GET
    expectStatus: 200
    linkable: false
    
